package Banque;

/**
* Banque/AgenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* vendredi 29 juin 2018 10 h 25 CEST
*/

public final class AgenceHolder implements org.omg.CORBA.portable.Streamable
{
  public Banque.Agence value = null;

  public AgenceHolder ()
  {
  }

  public AgenceHolder (Banque.Agence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Banque.AgenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Banque.AgenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Banque.AgenceHelper.type ();
  }

}
