package Banque;


/**
* Banque/Agence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* dimanche 1 juillet 2018 01 h 02 CEST
*/

public interface Agence extends AgenceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Agence
