package Banque;


/**
* Banque/AgenceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* dimanche 1 juillet 2018 01 h 02 CEST
*/

public interface AgenceOperations 
{
  String nom ();
  void nom (String newNom);
  Banque.Compte creerCompte (String login, String nom, String prenom, String pass, float solde, int nocompte);
  boolean supprimerCompte (String nom);
  Banque.Compte rechercherCompte (String nom);
  String afficherListeCompte ();
  String afficherInfoBanque ();
  boolean ConnexionBanque (String login, String pass);
} // interface AgenceOperations
