package Banque;


/**
* Banque/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* samedi 30 juin 2018 01 h 19 CEST
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
