package Banque;


/**
* Banque/AgenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* dimanche 1 juillet 2018 00 h 51 CEST
*/

abstract public class AgenceHelper
{
  private static String  _id = "IDL:Banque/Agence:1.0";

  public static void insert (org.omg.CORBA.Any a, Banque.Agence that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Banque.Agence extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Banque.AgenceHelper.id (), "Agence");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Banque.Agence read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AgenceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Banque.Agence value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Banque.Agence narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Banque.Agence)
      return (Banque.Agence)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Banque._AgenceStub stub = new Banque._AgenceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Banque.Agence unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Banque.Agence)
      return (Banque.Agence)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Banque._AgenceStub stub = new Banque._AgenceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
