package Banque;


/**
* Banque/AgenceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* vendredi 29 juin 2018 10 h 22 CEST
*/

public interface AgenceOperations 
{
  String nom ();
  void nom (String newNom);
  Banque.Compte creerCompte (String nom, int nocompte, float solde);
  boolean supprimerCompte (String nom);
  Banque.Compte rechercherCompte (String nom);
  String afficherListeCompte ();
  String afficherInfoBanque ();
  boolean ConnexionBanque (String login, String pass);
} // interface AgenceOperations
