package Banque;


/**
* Banque/CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* dimanche 1 juillet 2018 00 h 51 CEST
*/

public interface CompteOperations 
{
  String nomClient ();
  void nomClient (String newNomClient);
  String loginClient ();
  void loginClient (String newLoginClient);
  String passClient ();
  void passClient (String newPassClient);
  float solde ();
  boolean debiter (float somme, int nocompte);
  boolean crediter (float somme, int nocompte);
  boolean virement (float somme, int nocompte);
  String infosCompte ();
  void ajouterBenef (String nomBenef, String prenomBenef, int nocompte);
  String afficherBeneficiaire ();
  String afficherDebits ();
  String afficherCredits ();
  String afficherAjoutBeneficiaire ();
  String afficherVirements ();
} // interface CompteOperations
