package Banque;


/**
* Banque/CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* samedi 30 juin 2018 01 h 13 CEST
*/

public interface CompteOperations 
{
  String nomClient ();
  void nomClient (String newNomClient);
  float solde ();
  boolean debiter (float somme, int nocompte);
  boolean crediter (float somme, int nocompte);
  boolean virement (float somme, int nocompte);
  String infosCompte ();
  void ajouterBenef (String nomBenef, String prenomBenef, int nocompte);
  String afficherBeneficiaire ();
  String afficherDebits ();
  String afficherCredits ();
  String afficherAjoutBeneficiaire ();
  String afficherVirements ();
} // interface CompteOperations
