package Banque;


/**
* Banque/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from specification.idl
* dimanche 1 juillet 2018 00 h 51 CEST
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
